apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: scraper-hpa
  namespace: default
spec:
  maxReplicas: 1
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: scraper-deployment
  targetCPUUtilizationPercentage: 80
