apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: scraper-worker-hpa
  namespace: default
spec:
  maxReplicas: 10 
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: scraper-worker-deployment
  targetCPUUtilizationPercentage: 80
